### ISSUE TITLE
zenodo doi reference incorrect

### ISSUE THREAD

**Issue by jmoldon** [katiebreivik/hush#18]
I think this zenodo link is not right:
https://github.com/katiebreivik/hush/blob/48e38ef3fd478a4614b55d9e3b7f0eb30d565d88/showyourwork.yml#L6

The workflow seems to work when using this other one:

```
  10.5281/zenodo.7144944:
```

**Comment by katiebreivik** [comment]
Thanks for this @jmoldon! We are in the process of migrating to the final data sets, so things are a bit wonky with the zenodo links. I'll close this issue once everything is all connected properly.

**Comment by katiebreivik** [comment]
We should have everything connected properly now.
