### ISSUE TITLE
Showcase this paper on the showyourwork docs?

### ISSUE THREAD

**Issue by rodluger** [katiebreivik/hush#7]
Hey @katiebreivik, would you be interested in showcasing this paper on the [showyourwork documentation](https://showyourwork.readthedocs.io/en/stable/projects/)? It's just a matter of entering the metadata in [this JSON file](https://github.com/rodluger/showyourwork/blob/main/docs/projects.json) via a PR.

**Comment by katiebreivik** [comment]
This is fixed and I forgot to close it!
